
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.lang.String;

public class VendingMachine {

    private float totalCredit = 0f;

    private String machineMessage = "INSERT COIN";
    private boolean firstCheckOfMessageAfterMakingSelection = false;

    private float NICKEL_VALUE = 0.05f;
    private float DIME_VALUE = 0.1f;
    private float QUARTER_VALUE = 0.25f;
    private float UNACCEPTED_COIN_VALUE = 0f;

    private final String COLA_SELECTION = "cola";
    private final String CHIPS_SELECTION = "chips";
    private final String CANDY_SELECTION = "candy";
    private final String NO_SELECTION = "";
    private String selection = NO_SELECTION;

    private final float COLA_COST = 1.0f;
    private final float CHIPS_COST = 0.5f;
    private final float CANDY_COST = 0.65f;
    private final float NO_CREDIT = 0f;
    private float costOfSelection = NO_CREDIT;

    public void addCoin(String coin) {
        totalCredit += getCoinValue(coin);
        return;
    }

    public float getCoinValue(String coin) {
        if (coin == "nickel") {
            return NICKEL_VALUE;
        }
        else if (coin == "dime") {
            return DIME_VALUE;
        }
        else if (coin == "quarter") {
            return QUARTER_VALUE;
        }
        else {
            return UNACCEPTED_COIN_VALUE;
        }
    }

    public float getTotalCredit() {
        return totalCredit;
    }

    public String getMachineMessage() {
        setMachineMessage();
        return machineMessage;
    }

    public void selectItem(String item) {
        changeMessagePerSelection(item);
    }

    public void changeMessagePerSelection(String item) {
        if (item == COLA_SELECTION) {
            selection = COLA_SELECTION;
            costOfSelection = COLA_COST;
            firstCheckOfMessageAfterMakingSelection = true;
        }
        else if (item == CHIPS_SELECTION) {
            selection = CHIPS_SELECTION;
            costOfSelection = CHIPS_COST;
            firstCheckOfMessageAfterMakingSelection = true;
        }
        else if (item == CANDY_SELECTION) {
            selection = CANDY_SELECTION;
            costOfSelection = CANDY_COST;
            firstCheckOfMessageAfterMakingSelection = true;
        }
    }

    public void setMachineMessage() {
        if (firstCheckOfMessageAfterMakingSelection) {
            firstCheckOfMessageAfterMakingSelection = false;
            if (totalCredit < costOfSelection) {
                machineMessage = "PRICE: $" + String.format("%.2f", costOfSelection);
            }
            else if (totalCredit >= costOfSelection) {
                machineMessage = "THANK YOU";
                selection = NO_SELECTION;
                totalCredit = NO_CREDIT;
            }
        }
        else {
            if (totalCredit == NO_CREDIT) {
                machineMessage = "INSERT COIN";
            }
            else if (totalCredit < costOfSelection) {
                machineMessage = "CREDIT: $" + String.format("%.2f", totalCredit);
            }
            else {
                machineMessage = "INSERT COIN";
            }
        }
    }

    public String getSelection() {
        return selection;
    }
}