/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.lang.String;
public class VendingMachine {
    private float totalCredit = 0f;

    public void addCoin(String coin) {
        totalCredit += getCoinValue(coin);
        return;
    }

    public float getCoinValue(String coin) {
        if (coin == "nickel") {
            return 0.05f;
        }
        else if (coin == "dime") {
            return 0.1f;
        }
        else {
            return 0f;
        }
    }

    public float getTotalCredit() {
        return totalCredit;
    }
}
